### PR TITLE
Webpage improvements

### PR DESCRIPTION
**Pull request by AurelienLourot**
Hello :) I have made several improvements to the `index.html` to make it look very similar to official Dracula pages like https://draculatheme.com/gitk/

I hope you'll like it!

### CODE REVIEW

**Comment by gusbemacbe** [comment]
Ready and thanks. I analysed and approved. Your English is better than mine. Sorry for me speaking like a French. 

Can you explain why the reponsive typography is bad, for example, in case of `html`, applying --step*`?

**Comment by AurelienLourot** [comment]
No problem and thanks for the quick merge :) 

I found the `@media` things here not very necessary as without them the page still renders properly on mobile. What do you think?

For the `--stepUp*` things it looks like these things are used nowhere, or is it a feature that I just don't know?

**Comment by gusbemacbe** [comment]
> I found the @media things here not very necessary as without them the page still renders properly on mobile. What do you think?
> 

It is all good on both desktop and mobile.
> For the --stepUp* things it looks like these things are used nowhere, or is it a feature that I just don't know?

It is a fluid typography which resizes automatically the font sizes: https://css-tricks.com/snippets/css/fluid-typography/

**Comment by AurelienLourot** [comment]
:+1: but I mean here:

```
	/* Cada passo da escala é um poder de --ratio*/
	--stepUp1: calc(1em * var(--ratio));
	--stepUp2: calc(var(--stepUp1) * var(--ratio));
	--stepUp3: calc(var(--stepUp2) * var(--ratio));
```

you declared for example `stepUp3` but you use `stepUp3` nowhere, right?

**Comment by AurelienLourot** [comment]
(I mean, search for `stepUp3` in your code somewhere else, you won't find it :) )

**Comment by gusbemacbe** [comment]
Thank you for pointing out my mistake. I will pay attention for not making mistakes in the next projects.

**Comment by AurelienLourot** [comment]
Actually it's fine on my smartphone

screenshot

But you're right, I can imagine it to be wrapped on smaller screens. I'll create a pull-request in a few minutes in which I add the "Contributors" section and resurrect the fluid typography. 

Thanks :)

**Comment by AurelienLourot** [comment]
I see now what you mean, you're right :) 

I'll create now a new pull-request. I have re-inserted a slightly fluid typography (only from 14 to 16px) and I have tested it. It behaves nicely.

**Pull request merged**
